### ISSUE TITLE
好像不行

### ISSUE THREAD

**Issue by eicky** [Kimiato/DriveDirectLink#1]
gd链接是：https://drive.google.com/file/d/1gwbp_kwqzodZ4ODUTqHK7tmcGL04f5Ms/view?usp=sharing

转换后的连接：https://214214.xyz/tools/dlink/?id=1gwbp_kwqzodZ4ODUTqHK7tmcGL04f5Ms

打开直接提示
Bad Request
Error 400

**Comment by eicky** [comment]
但是之前那个大佬的可以，https://gdlink.vrt.app/?id=1gwbp_kwqzodZ4ODUTqHK7tmcGL04f5Ms

**Comment by jimu5** [comment]
已处理，现在可以用了。

**Comment by eicky** [comment]
你这是跳回原大佬的连接去了？

**Comment by jimu5** [comment]
需要确认下载的大文件先暂时跳到他的cf worker链接里面，
谷歌网盘下载大文件需要验证cookie。否则拒绝访问。
回头再写一个直接调用谷歌api的。到时候就可以直接下载了。
抱歉，先暂时这样处理了，后续会更新。

**Comment by eicky** [comment]
好吧，大佬加油
