### ISSUE TITLE
cf-worker脚本问题

### ISSUE THREAD

**Issue by veip007** [Kimiato/DriveDirectLink#2]
cf-worker脚本添加后，页面打开是空白（如：https://gdzl.12345.workers.dev/）
config.php配置更改之后（刚才CF的空白页地址如：https://gdzl.12345.workers.dev/）
仍旧使用作者的cf直连地址

**Comment by jimu5** [comment]
已更正cf-worker脚本。

页面空白不影响使用。

**Comment by veip007** [comment]
config.php配置更改之后（刚才CF的空白页地址如：https://gdzl.12345.workers.dev/）
仍旧使用作者的cf直连地址
https://gd.kway.workers.dev/gd/1j7qTzS8U3OITgmEKeBCKBhdq5b6j8fla

cf-worker脚本已经更新为最新版，cf地址也能正常打开。下载仍然调用的你的cf地址~

**Comment by jimu5** [comment]
感谢反馈，已修复。
请拉取最新的functions.php文件替换即可
