### ISSUE TITLE
Not Working Properly

### ISSUE THREAD

**Issue by xcoders-hub** [Kimiato/DriveDirectLink#3]
Sometime it direct download the file but sometime it shows login to google screen and login. stuck after that. please solve this issue thanks.

**Comment by jimu5** [comment]
Sometimes Google Web Drive will restrict access to a cf node, so there will be an interface to log in. You can deploy multiple cf workers to avoid this situation.

**Comment by xcoders-hub** [comment]
Can you please tell me how can i do this.

**Comment by jimu5** [comment]
I will update a new version to support this function.

**Comment by xcoders-hub** [comment]
Okay dude thanks

**Comment by xcoders-hub** [comment]
Hii Dude waiting for update? 

Thanks for your time.

**Comment by xcoders-hub** [comment]
I  add more than 3 cf workers for testing but it still shows login screen. i thought there is an bug in cf workers/index.js file. please recheck it.

**Comment by jimu5** [comment]
Sorry, I have been busy recently. I will check for updates as soon as possible.

**Comment by xcoders-hub** [comment]
Okay dude excited for update.
