### ISSUE TITLE
Video Not download

### ISSUE THREAD

**Issue by xcoders-hub** [Kimiato/DriveDirectLink#4]
This code fails when try to download movie.

**Comment by jimu5** [comment]
I have tested it and it seems that there is no problem.
Can you provide more detailed information?

**Comment by xcoders-hub** [comment]
Try to downlaod any movie it just download a file and shows download failed instantly.

**Comment by jimu5** [comment]
I have created a demo video to test.
The Google Drive link is: 
https://drive.google.com/open?id=1zUXTOdO5E6h777xYiwBCsnrslYul5VQM
The direct link is: 
https://214214.xyz/tools/dlink/?id=1zUXTOdO5E6h777xYiwBCsnrslYul5VQM


It seems that there is no problem.

**Comment by xcoders-hub** [comment]
Try with large videos like movies.
